TEST_SCRIPTS=./pluginTest.tcl ./timeTest.tcl

MODE=CPP

export PROJECT_ROOT_DIR
LD_LIBRARY_PATH=$(PROJECT_ROOT_DIR)/TCL-CPP-Plugin-API/tcl8.0.5/lib
export LD_LIBRARY_PATH

include ../../makefile.include
include ../../../makefile.include
