TARGET_LIB=libTclCommand

EXPORT_INCLUDES=$(shell echo *.h *.hpp)
SOURCES=$(shell echo *.cpp)

MODE=CPP
TAGS_FILE=tcl_tools_tclCommand-c++.tags
SUPPRESSED_WARNINGS=unused-function


USE_TCL=YES

include ../../makefile.include
