TARGET_DYNAMIC_LIB=libTclTime

SOURCES=$(shell echo *.cpp)
EXPORT_INCLUDES=$(shell echo *.h )

MODE=CPP
TAGS_FILE=tcl_tools_tclTime-c++.tags

SUPPRESSED_WARNINGS=unused-function

LINKED_LIBS=libTclCommand libUtils

USE_TCL=YES

include ../../makefile.include
include ../../../makefile.include
