TARGET_DYNAMIC_LIB=libTclSignals
TARGET_LIB=libTclSignals

SOURCES=$(shell echo *.cpp)

MODE=CPP
TAGS_FILE=tcl_tools_tclSignals-c++.tags

SUPPRESSED_WARNINGS=unused-function

LINKED_LIBS=libTclCommand libUtils libIOInterface

USE_TCL=YES

include ../../makefile.include
